pydata/pandas-datareader

pandas_datareader/data.py, pandas_datareader/tests/test_data.py
https://github.com/pydata/pandas/commit/f88f15b60d4b50391b8a188cf05bbc4643d4f494
=> ENH add interval kwarg to get_data_yahoo

README.rst
=> CLN: Fix non printing character in README.rst

docs/source/remote_data.rst, pandas_datareader/data.py, pandas_datareader/tests/test_data.py
- Added yahoo-actions data_source to DataReader;
- Added get_data_yahoo_actions that returns a DataFrame containing
DIVIDEND and SPLIT corporate actions fetched from Yahoo! Finance;
- Added unit tests;
- Added documentation example.
=> Extended DataReader to fetch Dividends and Stock Splits from Yahoo!

pandas_datareader/data.py
=> API: Update Fama-French url

pandas_datareader/data.py, pandas_datareader/tests/test_data.py
If requested data source hasn't been implemented.
Fixes #64
=> CLN: Add NotImplementedError to DataReader

pandas_datareader/tests/test_data.py
=> TST: Remove extra 'test_get_quote_string'.

pandas_datareader/google/daily.py, pandas_datareader/utils.py, pandas_datareader/yahoo/actions.py, pandas_datareader/yahoo/daily.py, pandas_datareader/yahoo/quotes.py
=> ENH: Add _encode_url to improve readability of url construction

pandas_datareader/utils.py, pandas_datareader/yahoo/actions.py
=> ENH: Don't pause on first attempt.

setup.py
Should fix https://github.com/pydata/pandas-datareader/issues/97
=> Add google and yahoo module

setup.py
Try to fix https://github.com/pydata/pandas-datareader/issues/99
=> FIX find packages automatically

.travis.yml, pandas_datareader/wb.py
=> TST: Update tests to pandas 0.17.0rc2

docs/source/conf.py, docs/source/index.rst, docs/source/whatsnew.rst, docs/source/whatsnew/v0.2.0.txt
First draft of whatsnew for v0.2.0
#70
=> DOC: Added whatsnew section and v0.2.0.txt

pandas_datareader/__init__.py
=> Update version number to 0.2.0

pandas_datareader/data.py, pandas_datareader/tests/test_data.py
Sorry, caused by typo in #110.
=> BUG: DataReader with yahoo-action raises TypeError

pandas_datareader/data.py, pandas_datareader/famafrench.py, pandas_datareader/oecd.py, pandas_datareader/tests/test_famafrench.py
Applied #110 refactoring to Fama-French reader.
=> CLN: FamaFrenchReader

README.rst
See https://github.com/pydata/pandas-datareader/issues/119
=> DOC: Add a Landscape badge to show code quality

docs/source/cache.rst, docs/source/index.rst, docs/source/whatsnew/v0.2.1.txt
=> DOC: Add cache documentation

docs/source/whatsnew/v0.2.1.txt, pandas_datareader/__init__.py
=> REL: Release 0.2.1

pandas_datareader/tests/test_data.py, pandas_datareader/yahoo/actions.py
Should fix https://github.com/pydata/pandas-datareader/issues/137
Replaces PR https://github.com/pydata/pandas-datareader/pull/139
=> FIX Yahoo Actions with several symbols

docs/source/remote_data.rst, docs/source/whatsnew/v0.2.2.txt, pandas_datareader/base.py, pandas_datareader/data.py, pandas_datareader/edgar.py, pandas_datareader/tests/test_data.py, pandas_datareader/tests/test_edgar.py, setup.py
=> Adds retrieval of EDGAR master index.

docs/source/remote_data.rst, docs/source/whatsnew/v0.2.2.txt, pandas_datareader/compat/__init__.py, pandas_datareader/data.py, pandas_datareader/edgar.py, pandas_datareader/tests/test_data.py, pandas_datareader/tests/test_edgar.py
=> Added retrieval of EDGAR daily indices.

pandas_datareader/compat/__init__.py, pandas_datareader/tests/test_eurostat.py, pandas_datareader/tests/test_oecd.py
The tests error or fail, but the data pulls still work. I'll put together what I can find about data changes and file an issue tomorrow.
=> Fix Eurostat and OECD tests that fail.

pandas_datareader/base.py
=> CLN: Fix retry pause.

pandas_datareader/edgar.py
Having pulled the whole series of daily indices (again), I made some slight changes to make the downloading process and returned data a little nicer to work with.
1. `dtype`s are now specified when reading the CSVs. This helps prevent type issues when reading batches and appending them to an `HDFStore`.
2. Dates are now converted to `Timestamp` using `to_datetime`.
3. Date and CIK are now used as index variables.
4. FTP sessions are now ended with `.close()`, as some seemingly-stalled downloads are only waiting on the server to respond to `QUIT`.
=> Predictability and quality of life changes for EDGAR.

pandas_datareader/tests/test_eurostat.py
=> TST: Fix test_get_sts_cobp_a

pandas_datareader/base.py, pandas_datareader/google/options.py, pandas_datareader/tests/test_google_options.py, pandas_datareader/tests/test_yahoo_options.py, pandas_datareader/yahoo/options.py
=> CLN: Cleanup option reader

README.rst
In light of recent PR <a href="https://github.com/pydata/pandas/pull/13735#issuecomment-234804019">pydata/pandas#13735</a>.
=> DOC: Update README regarding io.data/wb

pandas_datareader/base.py
=> ENH: More explicit RemoteDataError

pandas_datareader/tests/test_edgar.py
=> TST Fix Edgar tests

pandas_datareader/tests/test_eurostat.py
=> TST: Fix EUROSTAT tests

pandas_datareader/tests/test_google_options.py
=> TST: Google Options len(dates)

pandas_datareader/tests/test_yahoo_options.py
Skip some Yahoo Options tests when Data not available
See #192
=> TST: Yahoo Options - skip tests

pandas_datareader/base.py
=> ENH: remove duplicate code _sanitize_dates and _init_session

.travis.yml, pandas_datareader/enigma.py, pandas_datareader/tests/test_enigma.py
=> FIX: Enigma DataReader failling under Python 3.5

.travis.yml, pandas_datareader/tests/test_base.py, pandas_datareader/tests/test_data.py, pandas_datareader/tests/test_famafrench.py, pandas_datareader/tests/test_fred.py, pandas_datareader/tests/test_google.py, pandas_datareader/tests/test_oecd.py, pandas_datareader/tests/test_tsp.py, pandas_datareader/tests/test_wb.py, pandas_datareader/tests/test_yahoo.py, pandas_datareader/tests/test_yahoo_options.py, pandas_datareader/wb.py
Closes https://github.com/pydata/pandas-datareader/issues/261
=> CLN: PEP8 cleanup and display flake8 version

docs/source/remote_data.rst, pandas_datareader/google/options.py, pandas_datareader/tests/test_edgar.py, pandas_datareader/tests/test_google_options.py, pandas_datareader/tests/test_yahoo_options.py, pandas_datareader/yahoo/options.py
Also added note to documentation to indicate EDGAR is broken until rewrite.
#269
=> TST: Skip EDGAR tests until rewrite

.travis.yml
=> TST: Add python3.6 and pandas 19.2

.gitignore
These weren't being ignored by Git when I opened the repository in IntelliJ.
=> MAINT: Add .idea and .iml to .gitignore

.travis.yml, pandas_datareader/tests/_utils.py, pandas_datareader/tests/test_base.py, pandas_datareader/tests/test_data.py, pandas_datareader/tests/test_edgar.py, pandas_datareader/tests/test_enigma.py, pandas_datareader/tests/test_eurostat.py, pandas_datareader/tests/test_famafrench.py, pandas_datareader/tests/test_fred.py, pandas_datareader/tests/test_google.py, pandas_datareader/tests/test_google_options.py, pandas_datareader/tests/test_nasdaq.py, pandas_datareader/tests/test_oecd.py, pandas_datareader/tests/test_tsp.py, pandas_datareader/tests/test_wb.py, pandas_datareader/tests/test_yahoo.py, pandas_datareader/tests/test_yahoo_options.py, tox.ini
=> MAINT: Remove nose dependency

conda.recipe/meta.yaml, pandas_datareader/io/tests/test_jsdmx.py, pandas_datareader/io/tests/test_sdmx.py
=> MAINT: Remove vestigial nose usages

pandas_datareader/io/tests/test_sdmx.py
=> MAINT: Patch flake8 error

.travis.yml, pandas_datareader/base.py, pandas_datareader/data.py, pandas_datareader/enigma.py, pandas_datareader/eurostat.py, pandas_datareader/famafrench.py, pandas_datareader/fred.py, pandas_datareader/google/options.py, pandas_datareader/google/quotes.py, pandas_datareader/io/jsdmx.py, pandas_datareader/io/sdmx.py, pandas_datareader/oanda.py, pandas_datareader/tsp.py, pandas_datareader/wb.py, pandas_datareader/yahoo/daily.py, pandas_datareader/yahoo/options.py, pandas_datareader/yahoo/quotes.py
Title is self-explanatory.  Also enable checks for `E501` on Travis.
=> MAINT: Remove E501 flake8 errors

pandas_datareader/compat/__init__.py, pandas_datareader/famafrench.py, pandas_datareader/io/util.py, pandas_datareader/nasdaq_trader.py, pandas_datareader/tests/test_google.py, pandas_datareader/tests/test_yahoo_options.py, pandas_datareader/yahoo/options.py
Title is self-explanatory.  Everything should be nice and green now.
=> TST, COMPAT: Patch failing 0.20.* tests

pandas_datareader/tests/test_wb.py
This corrects one of the build failures.
=> Correct test_wdi_download

pandas_datareader/_testing.py
Ensure string version of message is printed when skipping a test
=> TST: Fix unprintable message when skipping

docs/source/whatsnew/v0.5.0.txt
=> REL: Release 0.5.0

pandas_datareader/famafrench.py, pandas_datareader/tests/google/test_options.py, pandas_datareader/tests/io/test_jsdmx.py, pandas_datareader/tests/test_famafrench.py, pandas_datareader/tests/test_oecd.py, pandas_datareader/tests/yahoo/test_options.py, pandas_datareader/tests/yahoo/test_yahoo.py, pandas_datareader/wb.py
Mark tests as xfail so that patches can start being merged
=> TST: Mark currently failing tests as xfail

pandas_datareader/data.py, pandas_datareader/moex.py, pandas_datareader/tests/test_moex.py
Added MOEX source:
https://en.wikipedia.org/wiki/Moscow_Exchange
https://moex.com/en/
https://iss.moex.com/iss/reference/?lang=en
=> Added MOEX data source (Moscow Exchange)

pandas_datareader/bankofcanada.py, pandas_datareader/base.py, pandas_datareader/data.py, pandas_datareader/tests/test_bankofcanada.py
=> REBASE: Dwrpayne/bankofcanada

pandas_datareader/io/jsdmx.py, pandas_datareader/oecd.py, pandas_datareader/tests/test_data.py, pandas_datareader/tests/test_fred.py, pandas_datareader/tests/test_oecd.py, pandas_datareader/tests/yahoo/test_options.py, pandas_datareader/tests/yahoo/test_yahoo.py
=> Fix failing tests

pandas_datareader/data.py, pandas_datareader/edgar.py, pandas_datareader/enigma.py, pandas_datareader/famafrench.py, pandas_datareader/io/sdmx.py, pandas_datareader/moex.py, pandas_datareader/nasdaq_trader.py, pandas_datareader/tsp.py, pandas_datareader/wb.py
=> Fix tsp default

pandas_datareader/tests/test_wb.py, pandas_datareader/wb.py
Update to v2
Fix small change in test
closes #421
=> CLN: Update WorldBank endpoint

.github/PULL_REQUEST_TEMPLATE.md
Ensure PRs add what's new entry
[skip ci]
=> BLD: Enforce what's new entry

README.rst, docs/source/conf.py, docs/source/readers/iex.rst, docs/source/remote_data.rst, docs/source/whatsnew/v0.6.0.txt, pandas_datareader/bankofcanada.py, pandas_datareader/base.py, pandas_datareader/enigma.py, pandas_datareader/eurostat.py, pandas_datareader/famafrench.py, pandas_datareader/fred.py, pandas_datareader/google/daily.py, pandas_datareader/google/quotes.py, pandas_datareader/iex/__init__.py, pandas_datareader/iex/daily.py, pandas_datareader/iex/deep.py, pandas_datareader/iex/market.py, pandas_datareader/iex/ref.py, pandas_datareader/iex/stats.py, pandas_datareader/iex/tops.py, pandas_datareader/moex.py, pandas_datareader/oecd.py, pandas_datareader/quandl.py, pandas_datareader/stooq.py, pandas_datareader/tsp.py, pandas_datareader/wb.py, pandas_datareader/yahoo/quotes.py
Large doc string clean up.
Ensure all function have at least a minimal doc string.
Set release date target
Clarify Google finance function
=> DOC: Clean up docs

pandas_datareader/_utils.py, pandas_datareader/tests/test_bankofcanada.py
Verify start <= end
Fix bug in bank of canada tests
=> BUG: Verify start <= end

.travis.yml, README.rst, docs/source/readers/index.rst, docs/source/readers/morningstar.rst, docs/source/remote_data.rst, docs/source/whatsnew/v0.6.0.txt, pandas_datareader/bankofcanada.py, pandas_datareader/mstar/daily.py, pandas_datareader/stooq.py
Final changes to documentation
=> DOC: Finalize documentation for 0.6.0 release

README.rst
=> DOC: Fix typo in readme

pandas_datareader/mstar/daily.py, pandas_datareader/tests/mstar/test_daily.py
=> BUG: Fix order of columns in morningstar

.coveragerc, pandas_datareader/base.py, pandas_datareader/compat/__init__.py, pandas_datareader/tests/test_tiingo.py, pandas_datareader/tiingo.py
Add tests for missed functions to tiingo
Remove edgar from coverage
=> TST: Add additional tests to tiingo

docs/source/whatsnew/v0.7.0.txt, pandas_datareader/data.py, pandas_datareader/yahoo/daily.py
Adds back support for downloading price data (not actions yet) from Yahoo! (New to github, not sure I'm doing everything right.)
=> Fix Yahoo! price data

pandas_datareader/iex/daily.py
=> MAINT: Remove unneeded `print` in IEXDaily reader

pandas_datareader/tests/test_fred.py
=> Correct FRED unit test

pandas_datareader/tests/test_iex_daily.py
=> Correct IEX unit test

pandas_datareader/tests/test_iex_daily.py
https://github.com/pydata/pandas-datareader/pull/511
=> Correct flake8 errors

docs/source/remote_data.rst, docs/source/whatsnew/v0.7.0.txt, pandas_datareader/data.py, pandas_datareader/tests/yahoo/test_yahoo.py, pandas_datareader/yahoo/quotes.py
=> BUG: Fix yahoo quotes API

docs/source/whatsnew/v0.7.0.txt, pandas_datareader/yahoo/daily.py
=> fixed issue when yahoo test failes because of time offset issues

pandas_datareader/tests/test_famafrench.py
=> TST: Repaired failing Fama-French test

README.rst
Should be the last item needed.
=> DOC: Updated README for 0.7.0 release

docs/source/cache.rst, docs/source/remote_data.rst, docs/source/whatsnew/v0.7.0.txt, pandas_datareader/__init__.py, pandas_datareader/fred.py
Add missing imports
Remove use of .ix
Fix typo
=> DOC: Fix documentation errors

pandas_datareader/tests/yahoo/test_yahoo.py
=> TST: Change dividend actions test to AAPL

pandas_datareader/tests/test_stooq.py
=> ENH: Update stooq test to include index

docs/source/readers/enigma.rst
Small typo change in RST file. No change to python code.
=> Correct typo Engima -> Enigma

pandas_datareader/av/__init__.py
This changes a single line that had a typo, that's all.
=> Correct typo

pandas_datareader/yahoo/actions.py
Per (https://github.com/pandas-dev/pandas/pull/20613)
=> COMPAT: Added explicit sort parameter to pd.concat in Yahoo Actions

docs/source/readers/index.rst, docs/source/remote_data.rst, docs/source/whatsnew/v0.8.0.txt, pandas_datareader/robinhood.py, pandas_datareader/tests/test_robinhood.py
=> CLN/REF: Mark deprecated Robinhood API

docs/source/whatsnew/v0.7.0.txt, pandas_datareader/bankofcanada.py, pandas_datareader/base.py, pandas_datareader/compat/__init__.py, pandas_datareader/enigma.py, pandas_datareader/eurostat.py, pandas_datareader/famafrench.py, pandas_datareader/google/quotes.py, pandas_datareader/io/jsdmx.py, pandas_datareader/io/sdmx.py, pandas_datareader/io/util.py, pandas_datareader/oecd.py, pandas_datareader/wb.py, pandas_datareader/yahoo/fx.py, pandas_datareader/yahoo/quotes.py
Remvoe dep on pandas.compat for 0.7.2 release
=> BUG: Remove pandas.compat dependencies

requirements-dev.txt, requirements.txt
=> BLD: Add requirements-dev for development environment setup

docs/source/remote_data.rst, docs/source/whatsnew/v0.8.0.txt, pandas_datareader/av/time_series.py, pandas_datareader/data.py, pandas_datareader/tests/av/test_av_time_series.py
=> ENH: Add intraday time series for alpha vantage

.travis.yml, README.rst, docs/source/whatsnew/v0.8.0.txt
Add codecov
Add Python 3.7 testing
=> MAINT: Add codecov and Python 3.7

.travis.yml, ci/pypi-install.sh, pandas_datareader/econdb.py, requirements-dev.txt, setup.cfg
Remove conda and use system python
Bump minimum supported versions
=> MAINT: Switch to PyPI and bump min versions

README.rst
No longer seems to work
https://github.com/jupyter/kernel_gateway/pull/316
=> Remove Landscape.io from README

pandas_datareader/av/__init__.py, pandas_datareader/tests/av/test_av_forex.py, pandas_datareader/tests/av/test_av_quotes.py, pandas_datareader/tests/av/test_av_sector.py, pandas_datareader/tests/av/test_av_time_series.py
https://travis-ci.com/gliptak/pandas-datareader/jobs/235398520
```
pandas_datareader/tests/av/test_av_forex.py list index out of range
.list index out of range
...
pandas_datareader/tests/av/test_av_quotes.py ....x
pandas_datareader/tests/av/test_av_sector.py .
pandas_datareader/tests/av/test_av_time_series.py ........
```
=> Correct AlphaVantage data source

README.rst
=> DOC: Add black badge

.travis.yml, pandas_datareader/base.py, pandas_datareader/compat/__init__.py, pandas_datareader/tests/test_eurostat.py, pandas_datareader/tests/test_wb.py, requirements.txt, setup.cfg, setup.py, tox.ini
Update requirements to reflect testing
=> MAINT: Update requirements

.github/PULL_REQUEST_TEMPLATE.md, .travis.yml, ci/pypi-install.sh, pandas_datareader/_version.py, pandas_datareader/base.py, pandas_datareader/compat/__init__.py, pandas_datareader/data.py, pandas_datareader/moex.py, pandas_datareader/tests/io/test_jsdmx.py, pandas_datareader/tests/yahoo/test_options.py, pandas_datareader/yahoo/daily.py, setup.cfg
Restore flake8 tests to improve code quality
=> MAINT: Restore flake8

docs/requirements.txt
=> DOC: Add a requirements file in docs

.travis.yml, docs/source/whatsnew/v0.8.0.txt, pandas_datareader/base.py
Catch empty DataFrame and report a warning
closes #640
=> BUG: Catch empty DataFrame

README.rst, docs/source/remote_data.rst, docs/source/whatsnew/v0.8.0.txt
=> DOC: Update dependency & breaking changes documentation

ci/pypi-install.sh, docs/requirements.txt, requirements-dev.txt, requirements.txt
https://github.com/pydata/pandas-datareader/issues/694
=> Make requirements more specific

.codecov.yml
https://docs.codecov.io/docs/ignoring-paths
=> Ignore tests for codecov

.codecov.yml
https://codecov.io/gh/gliptak/pandas-datareader/tree/316b2823385b18f92831926b5e3ecf1ab0f9bdfe/pandas_datareader
https://github.com/pydata/pandas-datareader/pull/700
=> Ignore tests for codecov (2)

setup.py, versioneer.py
Blacken ``setup.py`` and ``versioneer.py`` for consistency
=> STY: Blacken top-level config files

.codecov.yml
Continue to cover all of pdr but use a threshold of 1%
=> MAINT: Refactor codecov control

docs/source/whatsnew/v0.8.0.txt
Add doc to release and a commit to start v0.9.0
=> DOC: Add date to release

MANIFEST.in
Add requirements files to distribution
=> MAINT: Add requirements

docs/source/remote_data.rst
=> Correct Nasdaq symbols fields link

pandas_datareader/stooq.py, pandas_datareader/tests/test_stooq.py
=> fix for futures

pandas_datareader/econdb.py
=> update EcondbReader.read to use session

pandas_datareader/moex.py, pandas_datareader/tests/test_moex.py, testrunner.py
[+] Added a test for fixed functionality.
=> [BUG] Fixed a changed behavior of MOEX for shares data.

.travis.yml, README.rst, pandas_datareader/compat/__init__.py, pandas_datareader/moex.py, pandas_datareader/tests/test_tiingo.py, requirements-dev.txt, setup.py
=> Remove python 27

docs/source/remote_data.rst
=> make it more clear what TSP stands for

docs/source/whatsnew.rst, docs/source/whatsnew/v0.9.0.txt, pandas_datareader/tests/yahoo/test_yahoo.py, pandas_datareader/yahoo/daily.py
=> BUG: Fix Yahoo Splits for change in format

docs/source/see-also.rst
`Barchart is a data provider covering a ride range of...` --> `Barchart is a data provider covering a wide range of...`
=> Update typo on Barchart field in see-also.rst

pandas_datareader/compat/__init__.py, pandas_datareader/econdb.py, pandas_datareader/tests/test_econdb.py, pandas_datareader/tests/test_stooq.py, pandas_datareader/yahoo/daily.py
=> Fix tests and black formatting

.travis.yml, docs/source/conf.py, pandas_datareader/base.py, pandas_datareader/compat/__init__.py, pandas_datareader/data.py, pandas_datareader/econdb.py, pandas_datareader/iex/__init__.py, pandas_datareader/moex.py, pandas_datareader/robinhood.py, pandas_datareader/tests/test_base.py, pandas_datareader/tests/test_econdb.py, pandas_datareader/tests/test_robinhood.py, pandas_datareader/tests/test_utils.py, pandas_datareader/yahoo/components.py, pandas_datareader/yahoo/options.py, requirements.txt, setup.py, versioneer.py
=> Econdb master

README.rst, docs/requirements.txt, docs/source/conf.py, pandas_datareader/av/quotes.py, pandas_datareader/tests/av/test_av_quotes.py, pandas_datareader/tests/av/test_av_time_series.py, pandas_datareader/tests/test_iex_daily.py, pandas_datareader/tests/test_tsp.py, versioneer.py
=> MAINT: Fix IEX

docs/source/conf.py, pandas_datareader/data.py, pandas_datareader/naver.py, pandas_datareader/tests/test_naver.py
=> DOC: Use pydata theme everywhere

docs/source/whatsnew/v0.9.0.txt, pandas_datareader/tests/test_tsp.py, pandas_datareader/tsp.py
=> Support new TSP funds in 2020

pandas_datareader/tests/test_quandl.py
=> MAINT: Correct bug in Quandl testing

pandas_datareader/av/__init__.py, pandas_datareader/av/time_series.py, pandas_datareader/base.py, pandas_datareader/econdb.py, pandas_datareader/enigma.py, pandas_datareader/io/sdmx.py, pandas_datareader/oecd.py, pandas_datareader/tiingo.py, pandas_datareader/tsp.py, pandas_datareader/yahoo/daily.py, pandas_datareader/yahoo/fx.py, requirements-dev.txt
=> MAINT: Update black

pandas_datareader/tests/test_econdb.py
=> MAINT: Disable invalid test

ci/azure/azure_template_posix.yml, ci/azure/azure_template_windows.yml
=> MAINT: Remove paralle for Azure

pandas_datareader/nasdaq_trader.py
=> Use parameter name ("sep") in read_csv to comply to newer pandas version

README.md, docs/source/conf.py, pandas_datareader/data.py, pandas_datareader/iex/deep.py, pandas_datareader/io/sdmx.py, pandas_datareader/nasdaq_trader.py, pandas_datareader/quandl.py, pandas_datareader/tests/yahoo/test_yahoo.py, pandas_datareader/yahoo/options.py
=> STY: Improve style

pandas_datareader/fred.py, pandas_datareader/moex.py, pandas_datareader/quandl.py
indicies -> indices
Utillity -> Utility
intiating -> initiating
=> Fixed typo in quandl.py moex.py  fred.py

ci/azure/azure_template_posix.yml, ci/azure/azure_template_windows.yml, pandas_datareader/base.py, pandas_datareader/compat/__init__.py, pandas_datareader/data.py, pandas_datareader/famafrench.py, pandas_datareader/fred.py, pandas_datareader/iex/daily.py, pandas_datareader/moex.py, pandas_datareader/stooq.py, pandas_datareader/tests/test_bankofcanada.py, pandas_datareader/tests/test_famafrench.py, pandas_datareader/tests/test_fred.py, pandas_datareader/tests/test_stooq.py, pandas_datareader/tsp.py, pandas_datareader/wb.py, pandas_datareader/yahoo/daily.py, pandas_datareader/yahoo/headers.py, pandas_datareader/yahoo/options.py, pandas_datareader/yahoo/quotes.py, pyproject.toml, requirements-dev.txt
Fix issues in FRED and FamaFrench
=> MAINT: Fix PDF for pandas 3 changes
