pandas_datareader/tests/test_data.py
=> TST: Make tests work on python 2.6

pandas_datareader/data.py, pandas_datareader/tests/test_data.py
Fixes #8 
based on: pydata/pandas#9026
=> BUG: Datareader index name shows unicode characters

pandas_datareader/data.py, pandas_datareader/tests/test_data.py
Fixes #7 
Based on PR: pydata/pandas#9198
=> BUG:Fix options strike price float conversions if comma.

pandas_datareader/data.py, pandas_datareader/tests/test_data.py
=> CLN: Refactor Options methods for underlying price and time.

pandas_datareader/data.py
This bug also makes the "raise IOError" line unreachable. You'll get an UnboundLocalError on rs instead, if all retries fail.
=> BUG: _retry_read_url retries connection even if successful

pandas_datareader/data.py, pandas_datareader/tests/data/yahoo_options3.html, pandas_datareader/tests/test_data.py
=> BUG: Fix crash on empty table

LICENSE.md, setup.py
Fixes #3 the name to pandas-datareader.
Corrects the license, url and contact info etc. for setup.py.
=> FIX correct license, package name and authors/email

README.rst
@dstephens99 Currently the readme is not nicely formatted on PyPI. And it is possible that it is just because of this formatting 'error'. 
Can you try this?
=> DOC small formatting change in readme

pandas_datareader/tests/test_wb.py, pandas_datareader/wb.py
World Bank provides latitude and longitude as strings (and an empty string as a missing value). It's inconvenient so, I parse it to floats. Additionally, I added some description to the `wb.get_countries` function.
=> parsing latitude and longitude in wb.get_countries

pandas_datareader/wb.py
Update convert_objects use to new syntax.
xref pydata/pandas#10265
=> UPD: Update for upstream changes in DataFrame.convert_objects

docs/source/remote_data.rst, pandas_datareader/famafrench.py, pandas_datareader/tests/test_data.py, pandas_datareader/tests/test_famafrench.py
* Added get_datasets_famafrench (requires bs4) : list all available datasets from FF
* Complete rewrite of get_data_famafrench. Can grab and parse all (so called) csv files from FF website. Also uses metadata in the files to generate documentation (see `DESCR` attribute)
* Moved tests for FF to their own file (https://github.com/pydata/pandas-datareader/pull/59) 
API change : indexes are now pandas.PeriodIndex for annual and monthly data, and pandas.DatetimeIndex otherwise.
Should fix https://github.com/pydata/pandas-datareader/issues/55 https://github.com/pydata/pandas-datareader/issues/20 https://github.com/pydata/pandas-datareader/issues/21 see also https://github.com/pydata/pandas/issues/8842
=> [ENH] Fama/French

pandas_datareader/_utils.py, pandas_datareader/base.py, pandas_datareader/oecd.py, pandas_datareader/tests/test_wb.py, pandas_datareader/wb.py
Closes #120 to remove ``urlopen``. 
Related #119, changed some default arg using ``list`` to ``None`` (and set them in the method).
CC @femtotrader
=> CLN: Cleanup WorldBank reader

docs/source/whatsnew/v0.2.1.txt, pandas_datareader/base.py, pandas_datareader/data.py, pandas_datareader/tests/test_data.py, pandas_datareader/yahoo/options.py, setup.py
Adds requests session to Options, increases options parsing by 4x by skipping read_html.
=> ENH: Add requests session to Options

README.rst, pandas_datareader/__init__.py, pandas_datareader/data.py
#117 
Easy fix for now, remains backwards compatible.  Now you can tab into the key functions and DataReader.
Thoughts?
=> ENH: Add functions to top level API

docs/source/remote_data.rst, docs/source/whatsnew.rst, docs/source/whatsnew/v0.2.2.txt, pandas_datareader/data.py, pandas_datareader/tests/test_data.py
The existing dividend support pulls dividends as part of actions, but it's often desirable (for me anyway) to have just the dividends (and to pull a large number of symbols). The functionality is already there in `YahooDailyReader`, and this PR just creates an option that exposes it in `DataReader`.
=> Added `data_source='yahoo-dividends'` option to DataReader.

pandas_datareader/famafrench.py
Should fix https://github.com/pydata/pandas-datareader/issues/48
This PR replaces https://github.com/pydata/pandas-datareader/pull/136
=> ENH: Add session parameter to get_available_datasets

.travis.yml, pandas_datareader/__init__.py, pandas_datareader/_utils.py, pandas_datareader/base.py, pandas_datareader/data.py, pandas_datareader/eurostat.py, pandas_datareader/famafrench.py, pandas_datareader/fred.py, pandas_datareader/io/__init__.py, pandas_datareader/io/jsdmx.py, pandas_datareader/io/sdmx.py, pandas_datareader/io/tests/test_jsdmx.py, pandas_datareader/io/util.py, pandas_datareader/oecd.py, pandas_datareader/tests/test_data.py, pandas_datareader/tests/test_eurostat.py, pandas_datareader/tests/test_oecd.py, pandas_datareader/tests/test_wb.py, pandas_datareader/wb.py, pandas_datareader/yahoo/components.py, pandas_datareader/yahoo/daily.py, pandas_datareader/yahoo/options.py, pandas_datareader/yahoo/quotes.py
This PR enables `flake8` with Travis and should help code cleanup chttps://github.com/pydata/pandas-datareader/issues/119
=> Add PEP8 with flake8

docs/source/remote_data.rst, docs/source/whatsnew.rst, docs/source/whatsnew/v0.2.3.txt, pandas_datareader/base.py, pandas_datareader/tests/test_base.py, pandas_datareader/tests/test_tsp.py, pandas_datareader/tsp.py, setup.py
I added a webscraper to put TSP fund data into a dataframe.  In order to import pandas_datareader on my machine I had to put a requirement requests>=2.3.0
=> Added webscraper for Thrift Savings Plan

pandas_datareader/tests/test_data.py, pandas_datareader/yahoo/options.py
Might fix https://github.com/pydata/pandas-datareader/issues/168
=> FIX strike prices > 1k

pandas_datareader/google/quotes.py, pandas_datareader/tests/test_yahoo_options.py
Fixed Travis Error in ``test_get_quote_stringlist``, which raises ``TypeError: data argument can't be an iterator``.
This makes CI pass except py2.6 / pandas 0.13.1 which looks to have a different issue.
=> COMPAT: Do not pass iterator as index

docs/source/remote_data.rst, docs/source/whatsnew/v0.2.3.txt, pandas_datareader/data.py, pandas_datareader/google/options.py, pandas_datareader/tests/test_google_options.py
=> Implement Google options functionality

docs/source/remote_data.rst, docs/source/whatsnew/v0.2.3.txt, pandas_datareader/google/quotes.py, pandas_datareader/tests/test_google.py
https://github.com/pydata/pandas-datareader/issues/184
https://github.com/pydata/pandas-datareader/pull/177
@femtotrader
=> Refactor GoogleQuotesReader

docs/source/whatsnew/v0.2.3.txt, pandas_datareader/_utils.py, pandas_datareader/eurostat.py, pandas_datareader/io/sdmx.py, pandas_datareader/tests/test_eurostat.py
Closes #149. 3 changes for Eurostat reader:
- Query now includes beginning/ending period to reduce the result size
- Support zip format which may Eurostat returns when the result is large. Zipping on Eurostat takes some time and it may causes timeout (60 sec)
- Raises understandable error when Eurostat can't return the result, like "Query size exceeds maximum limit" (the message Eurostat returns)
=> ENH: Retrieve zipped data from eurostat

.travis.yml
I think it will be better to first see if unit tests are passing before checking PEP8 conformance.
=> Permute tests and PEP8

pandas_datareader/yahoo/options.py
I happened to notice that dates were getting parsed in the reverse order for me. I suspect that was because of a locale issue and so I added an explicit format specifier for the dates which alleviates that problem.
=> Yahoo Options Added format specifier for date parsing of options.

pandas_datareader/base.py, pandas_datareader/edgar.py
Should help (maybe close!) #226
=> ENH: add a timeout parameter (EDGAR tests hanging)

docs/source/remote_data.rst
=> Update WB link

docs/source/remote_data.rst, pandas_datareader/__init__.py, pandas_datareader/data.py, pandas_datareader/enigma.py, pandas_datareader/tests/test_enigma.py
Usage:
```
import pandas_datareader as pdr
df = pdr.get_data_enigma('enigma.inspections.restaurants.fl')
```
If `ENIGMA_API_KEY` does not exist in your env, it can be supplied as the second arg:
```
import pandas_datareader as pdr
df = pdr.get_data_enigma('enigma.inspections.restaurants.fl', 'ARIAMFHKJMISF38UT')
```
=> Adds support for Enigma datasets

.travis.yml, pandas_datareader/_utils.py, pandas_datareader/base.py, pandas_datareader/enigma.py, pandas_datareader/tests/test_edgar.py, pandas_datareader/tests/test_enigma.py, pandas_datareader/tests/test_famafrench.py, pandas_datareader/tests/test_google_options.py
Adding pandas 0.19 on travis, removing too old versions. 
There are some failing tests which must be skipped for now. These are blockers to release 0.3 (#173). 
closes #248.
=> Compat: Support pandas 0.19

README.rst, docs/source/cache.rst
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
=> Convert readthedocs links for their .org -> .io migration for hosted projects

docs/source/remote_data.rst, pandas_datareader/data.py, pandas_datareader/nasdaq_trader.py, pandas_datareader/tests/test_nasdaq.py
Nasdaq provides a symbol list with all US equities,
listed on the Nasdaq and other exchanges on their
FTP site. This patch adds support for grabbing
that list.
The list isn't very larger (< 1 MB), so we cache it
to RAM within the process the first time we download it.
=> ENH: Add support for Nasdaq symbol list

pandas_datareader/tests/test_google_options.py, pandas_datareader/tests/test_yahoo_options.py, pandas_datareader/yahoo/options.py
=> BUG: Fix breaking API change in yahoo options

.travis.yml
Use `pytest` instead of `nose` per discussion in #304.
=> TST: Use pytest instead of nose

.travis.yml, pandas_datareader/compat/__init__.py, pandas_datareader/edgar.py
=> COMPAT: Make is_number import backwards-compat

pandas_datareader/_utils.py, pandas_datareader/compat/__init__.py, pandas_datareader/io/sdmx.py, pandas_datareader/tests/test_eurostat.py, pandas_datareader/tests/test_wb.py, pandas_datareader/wb.py
=> MAINT: Refactor more compat checks into compat init

.travis.yml, pandas_datareader/compat/__init__.py, pandas_datareader/tests/test_eurostat.py, pandas_datareader/tests/test_wb.py, pandas_datareader/wb.py
* Add pandas `0.20.1` and `master` to Travis.
* Drop `0.16.2` and Python 3.4 machines.
Closes #307.
=> TST: Add pandas wheels to Travis build

docs/source/whatsnew/v0.4.0.txt, setup.py
Title is self-explanatory.  Also modifies `setup.py` to reflect changes.
Per comment in #313.
=> DOC: Add doc for v0.4.0

pandas_datareader/tests/test_google.py, pandas_datareader/tests/test_google_options.py, pandas_datareader/tests/test_oanda.py, pandas_datareader/tests/test_wb.py, pandas_datareader/yahoo/options.py
Patches all failing tests due to actual test failures and not incompatibilities with newer versions of `pandas`.
Closes #303.
=> TST: Patch failing tests

pandas_datareader/io/tests/test_jsdmx.py, pandas_datareader/io/tests/test_sdmx.py, pandas_datareader/tests/test_base.py, pandas_datareader/tests/test_data.py, pandas_datareader/tests/test_edgar.py, pandas_datareader/tests/test_enigma.py, pandas_datareader/tests/test_eurostat.py, pandas_datareader/tests/test_famafrench.py, pandas_datareader/tests/test_fred.py, pandas_datareader/tests/test_google.py, pandas_datareader/tests/test_google_options.py, pandas_datareader/tests/test_oecd.py, pandas_datareader/tests/test_wb.py, pandas_datareader/tests/test_yahoo.py, pandas_datareader/tests/test_yahoo_options.py
Remaining instances are those where an `assert*` function was defined directly in the class.
=> TST: Remove self.assert* from testing

pandas_datareader/compat/__init__.py, pandas_datareader/io/tests/test_jsdmx.py, pandas_datareader/io/tests/test_sdmx.py, pandas_datareader/tests/test_base.py, pandas_datareader/tests/test_data.py, pandas_datareader/tests/test_edgar.py, pandas_datareader/tests/test_enigma.py, pandas_datareader/tests/test_eurostat.py, pandas_datareader/tests/test_famafrench.py, pandas_datareader/tests/test_fred.py, pandas_datareader/tests/test_google.py, pandas_datareader/tests/test_google_options.py, pandas_datareader/tests/test_nasdaq.py, pandas_datareader/tests/test_oecd.py, pandas_datareader/tests/test_tsp.py, pandas_datareader/tests/test_wb.py, pandas_datareader/tests/test_yahoo.py, pandas_datareader/tests/test_yahoo_options.py
Title is self-explanatory.  Now all build machines should not have issues testing due to incompatibilities.
=> COMPAT, TST: Remove tm.TestCase from testing

pandas_datareader/_testing.py, pandas_datareader/tests/google/test_options.py, pandas_datareader/tests/test_edgar.py, pandas_datareader/tests/test_enigma.py, pandas_datareader/tests/test_eurostat.py, pandas_datareader/tests/test_nasdaq.py, pandas_datareader/tests/test_wb.py, pandas_datareader/tests/yahoo/test_options.py
We have tests that might fail for reasons beyond our control. This decorator catches those exceptions and skips those tests when such an error is raised.
=> TST: Add skip_on_exception decorator

pandas_datareader/google/quotes.py
replace(',','')
this will facilitate the conversion from string to float, and avoid exception
=> remove string ',' in quote price

docs/source/remote_data.rst
I noticed that there were some typos in the markup for these links.
=> Fix link markup.

docs/source/whatsnew/v0.5.0.txt, pandas_datareader/base.py, pandas_datareader/tests/yahoo/test_yahoo.py
closes #342
add 'null' in lower case to na_values argument to read_csv
=> fix 'null' in lower case as a  missing value in the new Yahoo API, make compatible with the older pandas versions

docs/source/remote_data.rst, docs/source/whatsnew/v0.5.0.txt, pandas_datareader/data.py, pandas_datareader/quandl.py, pandas_datareader/tests/test_quandl.py
Completing https://github.com/pydata/pandas-datareader/pull/346
Closing https://github.com/pydata/pandas-datareader/pull/360
=> Added QuandlReader (plus tests and doc)

.travis.yml, pandas_datareader/tests/yahoo/test_yahoo.py
=> TST: fix testing for yahoo get_data_null_as_missing comparisons

pandas_datareader/tests/yahoo/test_yahoo.py, pandas_datareader/yahoo/daily.py
xref https://github.com/pydata/pandas-datareader/issues/356
=> Correct Yahoo period end timestamp calculation

docs/source/remote_data.rst, pandas_datareader/data.py, pandas_datareader/enigma.py, pandas_datareader/tests/test_enigma.py
Implements #376, and includes
- Updating `EnigmaReader`
- Updating tests
- Updating docs
- Updating the main `data.py` library.
The exact sunsetting date of `app.enigma.io` is not determined, but is coming soon.
=> Feature/Issue 376 Update EnigmaReader Data Connector

pandas_datareader/tests/google/test_google.py
Changing skip to mark.xfail per recommendation of @rsvp in #404
=> TST: Changed skip to mark.xfail in test_google

pandas_datareader/fred.py
Updated url to reflect the changes by fred.stlouisfed.org for downloading CSV.
=> New FRED URL

.travis.yml
Update pandas to use 0.19 as the minimum version
Maintenance only.
=> TST: Update pandas to minimum 0.19

docs/source/remote_data.rst, pandas_datareader/data.py, pandas_datareader/stooq.py, pandas_datareader/tests/test_stooq.py
=> Peijiche stooq

pandas_datareader/__init__.py, pandas_datareader/base.py, pandas_datareader/data.py, pandas_datareader/exceptions.py, pandas_datareader/iex/__init__.py, pandas_datareader/iex/deep.py, pandas_datareader/iex/market.py, pandas_datareader/iex/ref.py, pandas_datareader/iex/stats.py, pandas_datareader/iex/tops.py, pandas_datareader/tests/test_data.py, pandas_datareader/tests/test_iex.py
=> Rgkimball iex

pandas_datareader/base.py, pandas_datareader/tests/test_wb.py, pandas_datareader/wb.py
=> Kurtforrester base freq

pandas_datareader/data.py, pandas_datareader/exceptions.py, pandas_datareader/google/daily.py, pandas_datareader/tests/google/test_options.py, pandas_datareader/tests/test_data.py, pandas_datareader/tests/test_edgar.py, pandas_datareader/yahoo/components.py
Add immediate deprecation errors to Yahoo, Google Options and Quotes,
and EDGAR
Add warning to Google finance
=> CLN/REF: Mark deprecated API

pandas_datareader/data.py, pandas_datareader/iex/stats.py, pandas_datareader/tests/test_iex.py, pandas_datareader/yahoo/options.py
Correct super inovcation
Remove incorrect function calls (unreachable)
Avoid multiple import of same class
=> CLN: Remove landscape caught errors

docs/source/whatsnew/v0.6.0.txt
Update whatsnew with recent PR information
=> DOC: Update whatsnews

.travis.yml, docs/source/whatsnew/v0.6.0.txt
Add automatic docbuild and push to gh-pages
=> ENH: Add automatic doc build

pandas_datareader/google/daily.py, pandas_datareader/google/quotes.py, pandas_datareader/tests/test_iex.py
=> New google urls

docs/source/index.rst, docs/source/readers/bank-of-canada.rst, docs/source/readers/enigma.rst, docs/source/readers/eurostat.rst, docs/source/readers/famafrench.rst, docs/source/readers/fred.rst, docs/source/readers/iex.rst, docs/source/readers/index.rst, docs/source/readers/moex.rst, docs/source/readers/nasdaq-trader.rst, docs/source/readers/oecd.rst, docs/source/readers/quandl.rst, docs/source/readers/stooq.rst, docs/source/readers/tsp.rst, docs/source/readers/world-bank.rst, pandas_datareader/base.py, pandas_datareader/enigma.py, pandas_datareader/eurostat.py, pandas_datareader/famafrench.py, pandas_datareader/fred.py, pandas_datareader/moex.py, pandas_datareader/oecd.py, pandas_datareader/tsp.py, pandas_datareader/wb.py
Add connector-specific doc pages
=> DOC: Add doc pages for specific connectors

docs/source/remote_data.rst, pandas_datareader/data.py, pandas_datareader/iex/daily.py, pandas_datareader/tests/test_iex_daily.py
Added IEX Daily Reader for historical data from IEX [chart](https://iextrading.com/developer/docs/#chart).
- Added tests in tests/test_iex_daily.py
- Added entry to docs/source/readers/remote_data.rst
Have an actions (Dividends+Splits) as well as quotes (from [quote](https://iextrading.com/developer/docs/#quote)) reader as well, but waiting for some clarification from the provider regarding bug fixes with the API calls - the quote may not be necessary anyway with the recent inclusion of "iex-last".
=> Added IEX Daily Reader (Historical)

pandas_datareader/mstar/daily.py, pandas_datareader/tests/mstar/test_daily.py
Fix date conversion bug in Mstar which should be relative to 1900-1-1
=> BUG: Fix date conversion bug in Morningstar

docs/source/readers/index.rst, docs/source/readers/robinhood.rst, docs/source/remote_data.rst, docs/source/whatsnew/v0.6.0.txt, pandas_datareader/data.py, pandas_datareader/robinhood.py, pandas_datareader/tests/test_robinhood.py
Add support for reading quotes and historical from Robinhood
=> ENH: Add support for Robinhood API

docs/source/readers/index.rst, docs/source/readers/tiingo.rst, docs/source/remote_data.rst, docs/source/whatsnew/v0.6.0.txt, pandas_datareader/data.py, pandas_datareader/tests/test_tiingo.py, pandas_datareader/tiingo.py, requirements.txt
Add daily, quote and metadata readers for Tiingo
closes #390
=> ENH: Add readers for Tiingo data

.coveragerc
=> TST: Improve coverage reporting accuracy

docs/source/whatsnew/v0.7.0.txt, pandas_datareader/compat/__init__.py, pandas_datareader/quandl.py, pandas_datareader/tests/test_quandl.py
Add support for the Quandl API key
closes #484
=> BUG: Add API KEY for Quandl

docs/source/whatsnew/v0.7.0.txt, pandas_datareader/mstar/daily.py
Fixes #486. Certain Morningstar (index) tickers now use ``np.nan`` to indicate empty volume data. Thanks @ggomarr.
=> Repaired Morningstar volume for indicies

docs/source/remote_data.rst
Tiingo is missing a link in Table of Contents
=> Create a link to Tiingo description in ToC

docs/source/whatsnew/v0.7.0.txt, pandas_datareader/enigma.py
Adds support for optionally passing a custom `base_url` to the `EnigmaReader`. The default behavior will not change, but this will allow the reader to be used with dev/staging instances as well as custom deployments. The feature will also guard against any further domain changes such as in #376.
=> Allows user to input a custom base url to EnigmaReader

pandas_datareader/base.py
Restore header argument that was removed by #515
=> BUG: Restore header arguments

docs/source/readers/alphavantage.rst, docs/source/readers/index.rst, docs/source/remote_data.rst, docs/source/whatsnew/v0.7.0.txt, pandas_datareader/av/__init__.py, pandas_datareader/av/forex.py, pandas_datareader/av/quotes.py, pandas_datareader/av/sector.py, pandas_datareader/av/time_series.py, pandas_datareader/data.py, pandas_datareader/tests/av/test_av_forex.py, pandas_datareader/tests/av/test_av_quotes.py, pandas_datareader/tests/av/test_av_sector.py, pandas_datareader/tests/av/test_av_time_series.py
Adds support for nearly all of the AlphaVantage API endpoints.
- **``AVTimeSeriesReader``** - class to handle requests for data from the Stock Time Series endpoints
- top-level ``get_data_av``, for TIME_SERIES_DAILY
- ``av-daily`` for TIME_SERIES_DAILY
- ``av-daily-adjusted`` for TIME_SERIES_DAILY_ADJUSTED
- ``av-weekly`` for TIME_SERIES_WEEKLY
- ``av-weekly-adjusted`` for TIME_SERIES_WEEKLY_ADJUSTED
- ``av-monthly`` for TIME_SERIES_MONTHLY
- ``av-monthly-adjusted`` TIME_SERIES_MONTHLY_ADJUSTED
- **``AVQuotesReader``** - class to handle requests for Batch Stock Quotes using top-level ``get_quote_av``
- **``AVForexReader``** - class to handle FX Exchange Rates endpoint (``av-forex`` or top-level ``get_exchange_rate_av``)
- **``AVSectorPerformanceReader``** - class to handle Sector …
=> ENH: Add support for AlphaVantage API

docs/source/whatsnew/v0.7.0.txt, pandas_datareader/compat/__init__.py, pandas_datareader/fred.py, pandas_datareader/tests/google/test_google.py, pandas_datareader/tests/test_fred.py
Pandas 0.23 moves is_list_like
Add import to compat
=> COMPAT: Add forward compat for is_list_like

pandas_datareader/data.py
It looks like the conditionals in data.py for the Alphavantage readers were removed (probably by mistake?) in 350de89. This causes such readers to raise an error when called. This pull restores the correct conditional cases (see below link for diff which causes the problem).
https://github.com/pydata/pandas-datareader/commit/350de8907131ecb74ea885ca40528e099df0f576#diff-c777b33d76c2f7a353162630709f98e5L330
No docs entry needed as the readers have not yet been released.
=> BUG: Repaired Alphavantage connectors

docs/source/remote_data.rst, docs/source/whatsnew/v0.7.0.txt, pandas_datareader/google/daily.py, pandas_datareader/tests/google/test_google.py, pandas_datareader/tests/test_data.py
Add immediate deprecation error to Google finance daily reader. Seems as if the previous workaround has been shutdown. Will repair #536 if this is indeed determined to be the case.
=> CLN/REF: Mark deprecated Google finance API

pandas_datareader/tests/yahoo/test_yahoo.py
For some reason the provider now shows an extra dividend for BHP.AX on 10/27/98 which is incorrect.
```
action     value
1999-10-29  DIVIDEND  0.250000
1999-05-10  DIVIDEND  0.260000
1998-10-29  DIVIDEND  0.552327
1998-10-27  DIVIDEND  0.250000
1998-05-11  DIVIDEND  0.260000
1997-10-30  DIVIDEND  0.250000
1997-05-12  DIVIDEND  0.260000
```
Also, the 5/10/1993 dividend has now been corrected by the provider from ``0.3`` to ``0.21``.
Here's the correct BHP.AX actions info: http://www.mysharetrading.com/bhp-dividends
=> Repaired Yahoo actions tests

docs/source/whatsnew/v0.7.0.txt, pandas_datareader/moex.py
Now MOEX data connector supports multiple symbols in constructor:
```python
import pandas_datareader.data as web
df = web.DataReader(['USD000UTSTOM', 'SBER'], 'moex',
start='2017-07-01', end='2017-07-31')
```
closes #562
=> Multiple symbols for MOEX data connector

pandas_datareader/tests/test_fred.py
Provider data changed on 1/1/13 GDP data. Updated test to ensure all GDP data points are accounted for, rather than testing value of the single value.
=> TST: Repaired FRED test

docs/source/remote_data.rst, docs/source/whatsnew/v0.7.0.txt, pandas_datareader/mstar/daily.py, pandas_datareader/tests/mstar/test_daily.py, pandas_datareader/tests/test_data.py
Per the discussion in #557, Morningstar's support for their historical endpoint seems to have ended. Leaving this here if that is the case. Tests fail due to unrelated FRED issues which are repaired in #559.
=> CLN/REF: Mark Deprecated Morningstar API

docs/source/whatsnew.rst, docs/source/whatsnew/v0.7.0.txt, pandas_datareader/conftest.py, pandas_datareader/tests/io/test_jsdmx.py, pandas_datareader/tests/io/test_sdmx.py, pandas_datareader/tests/yahoo/test_options.py
Remove get_data_path from tests since it was dropped upstream
=> TST: Remove tm.get_data_path use

pandas_datareader/moex.py
Fixed an issue with passing pandas DataFrame object as a `symbols` parameter for Moex data connector:
```python
import pandas as pd
import pandas_datareader.data as web
symbols = pd.DataFrame(index=['SBER', 'USD000UTSTOM'])
df = web.DataReader(symbols, 'moex',
start='2017-07-01', end='2017-07-31')
```
=> Fixed an issue with passing pandas DataFrame as a parameter

README.rst, docs/source/whatsnew/v0.7.0.txt, pandas_datareader/_utils.py, requirements.txt, setup.py
``requests-file`` and ``requests-ftp`` are unused in any readers and undocumented. Seems as if they are not currently needed? Can add mounts back to session in future should it become necessary.
cc: @davidastephens
=> CLN: Remove unused requests dependencies

docs/source/whatsnew/v0.7.0.txt, pandas_datareader/tests/yahoo/test_yahoo.py, pandas_datareader/yahoo/daily.py
Fix Yahoo actions dividend adjustment
=> BUG: Yahoo actions adjustment is incorrect

pandas_datareader/data.py
Added extra verification for the data source.
=> Added extra check for verifying data source

docs/source/whatsnew/v0.8.0.txt, pandas_datareader/yahoo/daily.py
=> BUG: Fix dividend adjustment

pandas_datareader/stooq.py
`import pandas_datareader.data as web
f = web.DataReader('^DJI', 'stooq')`
Above code breaks because country code is pre-appended for any symbol. For index data (^dji, ^spx etc), there is no need to pre-append country code. This patch fixes that.
=> ENH: Bug fix for downloading index historicals.

pandas_datareader/tests/yahoo/test_yahoo.py, pandas_datareader/yahoo/daily.py
-Issue 1:  DataReader(symbol, 'yahoo-dividends', start, end) will have divided by zero error for some dividend stocks like "NTR". 
Root cause:  when the stock has event like "1/0 Stock Split", it will fail. 
The fix: do numerator check first before evaluating the split ratio. In the above case, it should be Splitratio=1
-Issue 2:  fixed a bug that failed dividend/split test case of "def test_yahoo_DataReader(self)" in tests/test_yahoo.py.
=> Fixed two dividend related issues

pandas_datareader/__init__.py, pandas_datareader/compat/__init__.py, pandas_datareader/data.py, pandas_datareader/famafrench.py, pandas_datareader/moex.py, pandas_datareader/stooq.py, pandas_datareader/tests/test_stooq.py, pandas_datareader/tests/yahoo/test_yahoo.py, pandas_datareader/yahoo/actions.py, pandas_datareader/yahoo/daily.py
Repair syntax error introduced in conflict resolution
closes #628
=> BUG: Fix syntax error

pandas_datareader/base.py, pandas_datareader/enigma.py, pandas_datareader/famafrench.py, pandas_datareader/moex.py, pandas_datareader/nasdaq_trader.py
=> Fix StringIO import

docs/source/whatsnew/v0.7.0.txt, pandas_datareader/bankofcanada.py, pandas_datareader/base.py, pandas_datareader/compat/__init__.py, pandas_datareader/enigma.py, pandas_datareader/eurostat.py, pandas_datareader/famafrench.py, pandas_datareader/io/jsdmx.py, pandas_datareader/io/sdmx.py, pandas_datareader/io/util.py, pandas_datareader/moex.py, pandas_datareader/nasdaq_trader.py, pandas_datareader/oecd.py, pandas_datareader/wb.py, pandas_datareader/yahoo/fx.py, pandas_datareader/yahoo/quotes.py
Merging 0.7.4 py2 compat changes into master in prep for 0.8.0
=> COMPAT: Repair PY2 issues

pandas_datareader/iex/daily.py, pandas_datareader/tests/test_iex_daily.py
Currently the minimum requested data is a full year.  This limits the request to more specific time frames.
The current functionality is undesirable because IEX is no longer unlimited.  After this change, for less than 6 days,  the cost is 50 messages.  Before it was over 3,000.
=> Limit data use

docs/source/whatsnew/v0.8.0.txt, pandas_datareader/av/time_series.py, pandas_datareader/tests/av/test_av_time_series.py
Per #662, Alphavantage now returns *descending* time series data. This PR reconciles this change with PDR and reverses the index to maintain ascending order as is standard. Ensures tests are passing.
=> BUG/TST: Adjust Alphavantage time series reader to account for descending ordering

pandas_datareader/base.py
In some rare situations the response provided by Requests does not provide an encoding for the response content (most probably because there is no content). In these cases the retry code of pandas-datareader fails do the assumption the encoding being present at all times.
This mini PR fixes this issue.
=> Handle case when response.encoding is None

pandas_datareader/eurostat.py, pandas_datareader/tests/test_eurostat.py
The eurostat tests should now be passing: the url had to be changed slightly and a column renamed.
Moving on to econdb, the test urls appear to be returning blank data: e.g.
https://www.econdb.com/api/series/?ticker=BLS_CU.CUSR0000SA0.M.US&format=json&page_size=500&expand=meta
@econdb would you mind confirming what has changed with the API when you have a moment.
Thanks,
Simon.
=> Making minor changes to eurostat and econdb

pandas_datareader/econdb.py, pandas_datareader/tests/test_econdb.py
Sets correct default query parameter before API requests.
Detailed documentation and usage examples to follow in 1 week.
=> Correct EcondbReader's API URL format

.travis.yml, ci/pypi-install.sh, pandas_datareader/econdb.py, pandas_datareader/tests/av/test_av_forex.py, pandas_datareader/tests/av/test_av_quotes.py, pandas_datareader/tests/av/test_av_sector.py, pandas_datareader/tests/av/test_av_time_series.py, pandas_datareader/tests/io/test_jsdmx.py, pandas_datareader/tests/io/test_sdmx.py, pandas_datareader/tests/test_bankofcanada.py, pandas_datareader/tests/test_base.py, pandas_datareader/tests/test_data.py, pandas_datareader/tests/test_econdb.py, pandas_datareader/tests/test_enigma.py, pandas_datareader/tests/test_eurostat.py, pandas_datareader/tests/test_famafrench.py, pandas_datareader/tests/test_fred.py, pandas_datareader/tests/test_moex.py, pandas_datareader/tests/test_quandl.py, pandas_datareader/tests/test_stooq.py, pandas_datareader/tests/test_tiingo.py, pandas_datareader/tests/test_tsp.py, pandas_datareader/tests/yahoo/test_yahoo.py, requirements.txt, setup.cfg
Split test so that travis can become meaningful
=> TST: Split tests into stable and unstable readers

pandas_datareader/tests/test_wb.py
Correcting https://travis-ci.org/pydata/pandas-datareader/jobs/585837426
```
def test_wdi_get_indicators(self):
result1 = get_indicators()
result2 = WorldBankReader().get_indicators()
session = requests.Session()
result3 = get_indicators(session=session)
result4 = WorldBankReader(session=session).get_indicators()
for result in [result1, result2, result3, result4]:
exp_col = pd.Index(['id', 'name', 'source', 'sourceNote',
'sourceOrganization', 'topics', 'unit'])
>           assert result.columns.equals(exp_col)
E           AssertionError: assert False
E            +  where False = <bound method Index.equals of Index(['id', 'name', 'unit', 'source', 'sourceNote', 'sourceOrganization',\n       'topics'],\n      dtype='object')>(Index(['id', …
```
=> Update WorldBank indicator format

docs/source/remote_data.rst, pandas_datareader/data.py, pandas_datareader/tests/test_enigma.py, pandas_datareader/tests/test_quandl.py
Use a decorator to deprecate access_key
closes #692
=> MAINT: Deprecate access_key

.travis.yml, README.rst, ci/pypi-install.sh, docs/contributors.py, docs/source/whatsnew/v0.8.0.txt
=> DOC: Finish docs for 0.8pre

docs/source/remote_data.rst, docs/source/whatsnew/v0.8.0.txt, pandas_datareader/_utils.py, pandas_datareader/av/time_series.py, pandas_datareader/base.py, pandas_datareader/iex/daily.py, pandas_datareader/moex.py, pandas_datareader/quandl.py, pandas_datareader/stooq.py, pandas_datareader/tests/test_base.py, pandas_datareader/tests/test_utils.py, pandas_datareader/tiingo.py, pandas_datareader/tsp.py, pandas_datareader/yahoo/daily.py
DNM: need to check docbuild and other readers
PoC re: https://github.com/pydata/pandas-datareader/pull/677#issuecomment-531997861
* Refactors ``_sanitize_dates`` to accept additional date formats (str, int, date, datetime, timestamp) and output a tuple of ``pandas.Timestamp``
* Adds ``default_start_date`` property to allow readers to specify a rolling default start date. ``_BaseReader`` defaults to 15 years. This can be changed (possibly to 5 years).
* Corrects AV and IEX readers to use this paradigm (AV provides "20+ years" so defaults to 20, IEX provides and defaults to 15 years).
=> BUG/ENH: Refactor date handling

pandas_datareader/_utils.py, pandas_datareader/av/time_series.py, pandas_datareader/base.py, pandas_datareader/data.py, pandas_datareader/iex/__init__.py, pandas_datareader/iex/daily.py, pandas_datareader/iex/deep.py, pandas_datareader/moex.py, pandas_datareader/quandl.py, pandas_datareader/stooq.py, pandas_datareader/tiingo.py, pandas_datareader/tsp.py, pandas_datareader/wb.py, pandas_datareader/yahoo/daily.py, pandas_datareader/yahoo/fx.py
Use the same docstring for all start/end
=> DOC: Use a uniform docstring structure

pandas_datareader/wb.py
```
from pandas_datareader import wb
>>> pandas_datareader.__version__
'0.8.0'
>>> ind = ['NY.GDP.PCAP.KD', 'IT.MOB.COV.ZS']
>>> dat = wb.download(indicator=ind, country='all', start=2015, end=2015).dropna()
/home/jovyan/.local/lib/python3.7/site-packages/pandas_datareader/wb.py:659: UserWarning: No results found from world bank. Indicator: IT.MOB.COV.ZS
warnings.warn(msg)
>>> dat
NY.GDP.PCAP.KD
country                        year                
Arab World                     2015     6430.464609
Caribbean small states         2015     9224.146707
Central Europe and the Baltics 2015    14327.577261
Early-demographic dividend     2015     3400.049930
East Asia & Pacific            2015     9227.673906
...                                             ...
Virgin Islands (U.S.)          2015 …
```
=> Update docstring as iso_code is not returned for WorldBank

pandas_datareader/tiingo.py
default_start_date in pandas_datareader/base.py is defined as 5 years before current date.
=> update documentation for start date

pandas_datareader/av/__init__.py
Now when the API rate limit is hit instead of the error being:
```
--> 81                 raise RemoteDataError()
82         df = df[sorted(df.columns)]
83         df.columns = [id[3:] for id in df.columns]
RemoteDataError: 
```
It will be:
```
pandas_datareader._utils.RemoteDataError: {'Note': 'Thank you for using Alpha Vantage! Our standard API call frequency is 5 calls per minute and 500 calls per day. Please visit https://www.alphavantage.co/premium/ if you would like to target a higher API call frequency.'}
```
=> Added better error logging for API limit threshold

pandas_datareader/base.py, pandas_datareader/iex/__init__.py
=> Handle pandas urlencode removal.

pandas_datareader/base.py
=> add timeout

pandas_datareader/stooq.py
Hey guys, lately I found StooqDailyReader cause a problem when I try to download data series like "10AUY.B". Here is an example of stooq.com url for Australian bond yield. https://stooq.com/q/?s=10auy.b
Hope this help you people!
=> Empty DataFrame on bond yields

pandas_datareader/tests/io/test_jsdmx.py, pandas_datareader/tests/io/test_sdmx.py, pandas_datareader/tests/test_econdb.py, pandas_datareader/tests/test_eurostat.py, pandas_datareader/tests/test_famafrench.py, pandas_datareader/tests/test_fred.py, pandas_datareader/tests/test_moex.py, pandas_datareader/tests/test_oecd.py, pandas_datareader/tests/test_wb.py, pandas_datareader/tests/yahoo/test_options.py, pandas_datareader/tests/yahoo/test_yahoo.py
Fix failing tests in econdb and moex
Black code
=> MAINT: Fix failing tests

pandas_datareader/enigma.py, pandas_datareader/tests/test_enigma.py
Due to change in their business model Enigma is no longer working
=> MAINT: Deprecate Enigma

docs/source/readers/index.rst, docs/source/readers/naver.rst, docs/source/remote_data.rst, pandas_datareader/data.py, pandas_datareader/naver.py, pandas_datareader/tests/test_naver.py
This PR adds abilities to fetch daily historical data from [Naver Finance](https://finance.naver.com), which serves Korean (KOSPI, KOSDAQ) market data.
=> Daily historical data from Naver Finance

README.rst, docs/source/index.rst
Restructure docs to emphasize contents over what's new
=> DOC: Restructure docs

docs/source/whatsnew/v0.9.0.txt
Apparently #722 did not add an entry to `docs/source/whatsnew/vLATEST.txt`, so I would like to amend `whatsnew/v0.9.0.txt`, if possible.
=> Revise whatsnew/v0.9.0.txt

docs/source/remote_data.rst, docs/source/whatsnew.rst, docs/source/whatsnew/v.0.9.1.txt, docs/source/whatsnew/v0.7.0.txt, docs/source/whatsnew/v0.8.0.txt, pandas_datareader/moex.py, pandas_datareader/tests/test_moex.py
Filters output using only data from the main board for every ticker (before that it was returning unuseful stats from repo boards and null values from boards, that were not main for the asset and had no trading history).
=> MOEX: Use data from the main board only for each ticker

pandas_datareader/tests/test_econdb.py, pandas_datareader/tests/test_eurostat.py, pandas_datareader/tests/test_fred.py, pandas_datareader/tests/test_oecd.py
Fixing tests.
pandas.testing.assert_series_equal now includes a default argument of [check_freq=True](https://github.com/pandas-dev/pandas/blob/master/pandas/_testing.py#L1217). With this new arg some of the tests are failing as the index.freq does not match in comparisons.
I've adjusted index.freq so that the tests pass. Another option is to use check_freq=False, but this argument is not available in earlier versions of pandas. Alternatively, we could inspect the function for the existence of check_freq and pass False if required. I considered changing index.freq to be the easiest option.
Thanks
=> Fixing tests for index.freq

pandas_datareader/tests/test_moex.py
It looks like extra columns are coming back from the api and causing the df.size assertion to fail. I've changed this to assert the number of rows == 2 for each of "GAZP", "SIBN".
Cheers
=> Fixed test_moex_stock_datareader

pandas_datareader/moex.py
There is a small typo in pandas_datareader/moex.py.
Should read `received` rather than `recevied`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, recevied -> received

pandas_datareader/compat/__init__.py
It seems like pandas (I am using v1.2.1) renamed `pandas.io.common.get_filepath_or_buffer` to `pandas.io.common._get_filepath_or_buffer` and changed its signature.
This makes, e.g., code like this crash:
```python
import pandas_datareader as pdr
pdr.data.DataReader('hlth_hlye', 'eurostat')
```
This PR makes `pandas_datareader.compat.get_filepath_or_buffer` use the new interface.
=> Fix usage of pandas.io.common.get_filepath_or_buffer

docs/source/index.rst
needs hyphens. 
http://www.thewriter.com/what-we-think/style-guide/to-hyphenate-or-not-to-hyphenate/#:~:text=When%20it%20comes%20after%20the,up%2Dto%2Ddate%20document.
only touched one line of the docs
=> grammar fix in docs (up-to-date instead of up to date)

pandas_datareader/tests/test_econdb.py, pandas_datareader/tests/test_eurostat.py, pandas_datareader/tests/test_quandl.py, setup.cfg
=> MAINT: Correct Eurostat tests

pandas_datareader/base.py, pandas_datareader/yahoo/daily.py
=> BUG: Correct behavior of yahoo

README.md
=> MAINT: Clean README

pandas_datareader/_utils.py, pandas_datareader/base.py, pandas_datareader/compat/__init__.py, pandas_datareader/naver.py, pandas_datareader/tests/test_econdb.py, pandas_datareader/tests/test_famafrench.py, pandas_datareader/tests/test_fred.py, pandas_datareader/tests/yahoo/test_options.py, pandas_datareader/tests/yahoo/test_yahoo.py, pandas_datareader/yahoo/_headers.py, pandas_datareader/yahoo/actions.py, pandas_datareader/yahoo/daily.py, pandas_datareader/yahoo/quotes.py, setup.cfg
Fix all broken Yahoo readers
Test against pandas 1
Change minimums
=> MAINT: Final fixes

docs/source/remote_data.rst
Currently the [list of supported sources](https://pandas-datareader.readthedocs.io/en/latest/remote_data.html) in [`remote_data.rst`](https://github.com/pydata/pandas-datareader/blob/main/docs/source/remote_data.rst) is not ordered alphabetically. It will be easier to find out a source if this list is alpahbetically ordered. This PR fixes that.
- Only change made in file: `remote_data.rst`
- This close #890.
=> Alphabetically order list of supported sources in remote_data.rst file

docs/source/remote_data.rst
volume was misspelled at line 746
=> fixed a character

pandas_datareader/compat/__init__.py
Silence the deprecation warnings by using `packaging`
=> Replace deprecated distutils with packaging

pandas_datareader/moex.py
Closes pydata/pandas-datareader#966
=> Fix 'DataFrame' object has no attribute 'append' error in MoexReader

pandas_datareader/stooq.py
_DailyBaseReader does not have the `freq` parameter.
=> Fix doc of StooqDailyReader freq argument
